In [127]:
import pandas as pd
import json
from pandas.io.json import json_normalize
import pymongo
from pymongo import MongoClient
import time
from tqdm import tqdm

In [48]:
str(time.time()).replace('.','_')

'1576030682_5906818'

In [57]:
#point the client at mongo URI
client = MongoClient('mongodb://root:root@localhost:27017')
#select database
db = client['AndroPyTool_database']
#select the collection within the database
test = db['report_1576033460-45']
#convert entire collection to Pandas dataframe
test = pd.DataFrame(list(test.find()))

In [86]:
df_norm = json_normalize(test.to_dict("records"), sep="-")

In [106]:
test['Receivers'][1]

{'wolf-uit-com-unlockbywave--setting-BootRecevicer': ['android.intent.action.BOOT_COMPLETED'],
 'com-ironsource-mobilcore-InstallationTracker': [],
 'wolf-uit-com-unlockbywave--view-AdminReceiver': ['android.app.action.DEVICE_ADMIN_ENABLED',
  'android.app.action.DEVICE_ADMIN_DISABLED'],
 'wolfsoftlib-com-push-ChangeStatus': ['android.net.conn.CONNECTIVITY_CHANGE',
  'android.view.InputMethod'],
 'wolf-uit-com-unlockbywave--setting-AlarmReceiver': []}

In [101]:
json_normalize(df_norm["Permissions"].to_dict(),record_path=[['Permissions']],sep="-")

KeyError: 'Permissions'

In [103]:
df_norm.filter(regex="^Ser")

Services-wolfsoftlib-com-push-MyService  \
0                                     NaN   
1                                      []   

  Services-wolf-uit-com-unlockbywave--ServiceUnlock  \
0                                               NaN   
1                        [android.view.InputMethod]   

  Services-com-ironsource-mobilcore-MobileCoreReport  \
0                                                NaN   
1                                                 []   

  Services-wolfsoftlib-com-push-BaseService  
0                                       NaN  
1                                        []

In [27]:
df = pd.read_json('/home/cristiankamia/androzoo/test/Features_files/aerouniflylaunchpad-analysis.json')


In [30]:
df['Static_analysis']['Strings']

{'Failed to retrieve mButtonDrawable field': 1,
 '<init>:android.content.Context:com.squareup.okhttp.OkHttpClient': 1,
 'Falling back to Crashlytics key lookup from Manifest': 1,
 'com.crashlytics.CrashSubmissionAlwaysSendTitle': 1,
 'New Collection violated the Collection spec': 1,
 'ReadablePartial objects must not have overlapping fields': 1,
 'op should be remove or update.': 1,
 'Intent with no response code, assuming OK (known issue)': 1,
 'FHCRC': 1,
 'SSL_RSA_WITH_DES_CBC_SHA': 1,
 'Use setFixedLengthStreamingMode() or setChunkedStreamingMode() for requests larger than 2 GiB.': 1,
 'Signature:': 1,
 'Querying SKU details.': 1,
 'INTNERNAL_ERROR': 1,
 'did not call through to super.onDetach()': 1,
 'mCurState=': 1,
 'Notification=>Error:': 1,
 'ACTION_PREVIOUS_HTML_ELEMENT': 1,
 'Another strategy was already registered:': 4,
 'unexpected encodedPath:': 1,
 ',instanceCreators:': 1,
 'android.support.PARENT_ACTIVITY': 1,
 'The calendar must not be null': 7,
 'The end instant must 

In [12]:
df = pd.read_json('../data/raw/test/OUTPUT_ANDROPY_1573012922.58.json',  orient='index')

In [10]:
df_norm = json_normalize(df_static.to_dict("list"), "Static_analysis", sep="-")

Pre_static_analysis  \
Filename                                      xyz.pusatku.kurs.apk   
md5                               d3fbba63aa0a1dc8f477884d458015bb   
sha256           ed883bcb8365cf8ec92bb9f49f0d6d15b22824006fdc21...   
sha1                      7d53f174554170f9928750c6c77fe8b818a9bf98   
VT_positives                                                  None   
Package name                                                   NaN   
Permissions                                                    NaN   
Opcodes                                                        NaN   
Main activity                                                  NaN   
API calls                                                      NaN   
Strings                                                        NaN   
API packages                                                   NaN   
System commands                                                NaN   
Intents                                                        NaN   
Activities                                                     NaN   
Services                                                       NaN   
Receivers                                                      NaN   

                                                   Static_analysis  \
Filename                                                       NaN   
md5                                                            NaN   
sha256                                                         NaN   
sha1                                                           NaN   
VT_positives                                                   NaN   
Package name                                      xyz.pusatku.kurs   
Permissions      [android.permission.VIBRATE, android.permissio...   
Opcodes          {'rem-float/2addr': 1, 'mul-float/2addr': 44, ...   
Main activity                        com.baseappfull.fwd.Dashboard   
API calls        {'android.view.View.restoreHierarchyState': 1,...   
Strings          {'\\\\t': 1, '\\\\r': 1, 'Unable to call the d...   
API packages     {'android.view': 704, 'android.support.v4.os':...   
System commands  {'service': 45, 'top': 1, 'sh': 3, 'start': 1,...   
Intents                          {'android.intent.action.MAIN': 1}   
Activities       {'com.baseappfull.fwd.Dashboard': ['android.in...   
Services                                                        {}   
Receivers                                                       {}   

                 Dynamic_analysis VirusTotal  
Filename                      NaN             
md5                           NaN             
sha256                        NaN             
sha1                          NaN             
VT_positives                  NaN             
Package name                  NaN             
Permissions                   NaN             
Opcodes                       NaN             
Main activity                 NaN             
API calls                     NaN             
Strings                       NaN             
API packages                  NaN             
System commands               NaN             
Intents                       NaN             
Activities                    NaN             
Services                      NaN             
Receivers                     NaN

In [3]:
df_s = df.iloc[:-2,:] 

In [4]:
df_s = df_s.T

In [40]:
test = test.T

In [41]:
test

0
_id                           5defc9153832160001d025d7
a    {'Static_analysis': {'Activities': {'w3appinfo...
b    {'Static_analysis': {'Activities': {'com-irons...

In [5]:
df_s

Pre_static_analysis  \
a2  {'Filename': 'a2.apk', 'md5': 'ec220753e11713b...   
a1  {'Filename': 'a1.apk', 'md5': '420076fc7690b49...   
a3  {'Filename': 'a3.apk', 'md5': 'cb700d67c2238dd...   

                                      Static_analysis  
a2  {'Package name': 'ac.za.cput.weboffice', 'Perm...  
a1  {'Package name': 'adnan.solution.phalonkfawaid...  
a3  {'Package name': 'a.kakao.iconnect.woodentalk'...

In [6]:
df_static = df_s.drop("Pre_static_analysis", axis=1)

In [7]:
df_static_f = json_normalize(df_static.to_dict("list"), "Static_analysis", sep="-")

In [8]:
%time df_api_packages = df_static_f.filter(regex="^API packa")

CPU times: user 68 ms, sys: 0 ns, total: 68 ms
Wall time: 63.6 ms


In [9]:
df_static_f

Package name  \
0          ac.za.cput.weboffice   
1  adnan.solution.phalonkfawaid   
2   a.kakao.iconnect.woodentalk   

                                         Permissions  \
0  [android.permission.INTERNET, android.permissi...   
1  [android.permission.INTERNET, android.permissi...   
2                                                 []   

                                  Main activity  Opcodes-rem-float/2addr  \
0               ac.za.cput.weboffice.CPUTMobile                      2.0   
1           adnan.solution.phalonkfawaid.Splash                      2.0   
2  com.iconnect.kakao.theme.sample.MainActivity                      NaN   

   Opcodes-mul-float/2addr  Opcodes-rem-int/2addr  Opcodes-array-length  \
0                      159                    1.0                   361   
1                      146                    NaN                  1068   
2                       36                    NaN                     2   

   Opcodes-div-int/lit8  Opcodes-sub-float/2addr  Opcodes-move  ...  \
0                    56                       38          1322  ...   
1                    92                       35          5244  ...   
2                     7                       12           217  ...   

   API calls-android.widget.EdgeEffect.onPull  \
0                                         NaN   
1                                         NaN   
2                                         1.0   

   API calls-android.view.FocusFinder.findNextFocus  \
0                                               NaN   
1                                               NaN   
2                                               1.0   

   API calls-android.support.v4.view.ViewPager.i  \
0                                            NaN   
1                                            NaN   
2                                            2.0   

   Strings-kakaotalk://settings/theme/  \
0                                  NaN   
1                                  NaN   
2                                  1.0   

   Strings-com.android.browser.application_id  \
0                                         NaN   
1                                         NaN   
2                                         2.0   

   Strings-\ud3f0\ud14c\ub9c8\uc0f5\uc774 \uc124\uce58\ub418\uc5b4 \uc788\uc5b4\uc57c \uc774\uc6a9\uac00\ub2a5\ud569\ub2c8\ub2e4.\n\ud3f0\ud14c\ub9c8\uc0f5 \uc124\uce58\ub97c \uc704\ud574 \ub9c8\ucf13\uc73c\ub85c \uc774\ub3d9 \ud569\ub2c8\ub2e4.  \
0                                                NaN                                                                                                                                                                                                    
1                                                NaN                                                                                                                                                                                                    
2                                                1.0                                                                                                                                                                                                    

   Strings-market://details?id=com.iconnect.app.pts.a&referrer=utm_source%3Dtheme_download%26utm_medium%3Dtheme  \
0                                                NaN                                                              
1                                                NaN                                                              
2                                                1.0                                                              

   Strings-\ud574\ub2f9 \uae30\ub2a5\uc744 \uc704\ud55c \uc571\uc744 \ucc3e\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4 :(  \
0                                                NaN                                                                   
1                                                NaN                   

In [10]:
json_normalize(df_static_f, "Permissions", sep="-")

TypeError: string indices must be integers

In [20]:
df_static_permissions = json_normalize(df_static_f.to_dict("split", "Permissions"))

TypeError: unsupported type: <class 'str'>

In [11]:
df_static_per

NameError: name 'df_static_per' is not defined

In [108]:
from sklearn.model_selection import train_test_split
import numpy as np

a = np.arange(10)
print(a)
# [0 1 2 3 4 5 6 7 8 9]

print(train_test_split(a))
# [array([8, 4, 9, 0, 6, 7, 2]), array([1, 5, 3])]

print(type(train_test_split(a)))
# <class 'list'>

print(len(train_test_split(a)))
# 2

[0 1 2 3 4 5 6 7 8 9]
[array([3, 8, 9, 2, 0, 4, 1]), array([5, 6, 7])]
<class 'list'>
2


In [109]:
train, test = train_test_split(a, test_size=None, train_size=0.7, random_state = 3)

In [110]:
train

array([2, 9, 6, 7, 0, 3, 8])

In [111]:
test

array([5, 4, 1])

In [112]:
train

array([2, 9, 6, 7, 0, 3, 8])

In [113]:
df_train_opcodes = pd.read_csv("../data/processed/train_opcodes.csv")

In [115]:
df_test_opcodes = pd.read_csv("../data/processed/test_opcodes.csv")

In [116]:
df_test_opcodes

OPCODE-rem-float/2addr  OPCODE-rem-int/2addr  OPCODE-array-length  \
0                          2                     3                  317   
1                          3                     2                  831   
2                          0                     0                  238   
3                          0                     0                    1   
4                          2                     1                  353   
...                      ...                   ...                  ...   
6596                       0                     3                  217   
6597                       0                     3                   78   
6598                       0                     4                  198   
6599                       0                     1                   62   
6600                       0                     3                   76   

      OPCODE-div-int/lit8  OPCODE-sub-float/2addr  OPCODE-and-int/lit8  \
0                     161                      87                  242   
1                      56                      33                   75   
2                      24                      25                   62   
3                       0                       0                    0   
4                      61                      34                  109   
...                   ...                     ...                  ...   
6596                   35                      24                   50   
6597                   34                      24                   25   
6598                   61                      79                   43   
6599                    5                       0                   11   
6600                    6                       7                   23   

      OPCODE-and-int  OPCODE-int-to-long  OPCODE-move-wide/from16  \
0                 40                  78                      170   
1                  4                  77                       73   
2                 10                  41                       35   
3                  0                   0                        0   
4                 17                  92                      131   
...              ...                 ...                      ...   
6596               3                  56                        0   
6597               6                  43                        8   
6598              11                  49                       26   
6599               1                   4                       11   
6600               0                   8                        9   

      OPCODE-mul-int/lit8  ...  OPCODE-packed-switch  OPCODE-mul-int  \
0                      56  ...                   154              47   
1                     286  ...                   424               5   
2                      21  ...                    70              13   
3                       0  ...                     0               0   
4                     131  ...                   278              26   
...                   ...  ...                   ...             ...   
6596                   28  ...                    44               2   
6597                   23  ...                    49              11   
6598                   58  ...                   111               3   
6599                    8  ...                   101               1   
6600                   24  ...                     6               2   

      OPCODE-shl-int  OPCODE-ushr-long/2addr  OPCODE-iget-object  \
0                 18                       1               18590   
1                  7                      22               52910   
2                  6                       0                9044   
3                  0                       0                   0   
4                 20                      11               15682   
...              ...                     ...                 ...   
6596               4                       1  

In [117]:
df_train_opcodes

OPCODE-rem-float/2addr  OPCODE-rem-int/2addr  OPCODE-array-length  \
0                           4                     5                  890   
1                           1                     6                  414   
2                           4                     1                  331   
3                           2                     8                  898   
4                           4                    14                 1322   
...                       ...                   ...                  ...   
15394                       3                     3                  618   
15395                       2                     2                  384   
15396                       0                     8                 1524   
15397                       0                     1                  133   
15398                      11                     5                  417   

       OPCODE-div-int/lit8  OPCODE-sub-float/2addr  OPCODE-and-int/lit8  \
0                      113                      76                  118   
1                      141                      99                  120   
2                       56                      37                  104   
3                      375                     226                  383   
4                      205                     144                  308   
...                    ...                     ...                  ...   
15394                   59                      31                   82   
15395                   75                      37                  162   
15396                  219                      74                  640   
15397                    0                       0                    5   
15398                   85                     263                 1024   

       OPCODE-and-int  OPCODE-int-to-long  OPCODE-move-wide/from16  \
0                  16                 117                       72   
1                   3                  51                       42   
2                  17                  34                       27   
3                  52                 313                      238   
4                  41                 363                      158   
...               ...                 ...                      ...   
15394              10                  69                       41   
15395              14                  89                       51   
15396              42                 222                       57   
15397               0                  29                        3   
15398              10                  58                       28   

       OPCODE-mul-int/lit8  ...  OPCODE-packed-switch  OPCODE-mul-int  \
0                      215  ...                   429              11   
1                      140  ...                    86              59   
2                       95  ...                   163              11   
3                      332  ...                   659              28   
4                      332  ...                   415              40   
...                    ...  ...                   ...             ...   
15394                  129  ...                   271              11   
15395                   67  ...                   130              17   
15396                  318  ...                   376              87   
15397                    4  ...                    17               0   
15398                  465  ...                   123              26   

       OPCODE-shl-int  OPCODE-ushr-long/2addr  OPCODE-iget-object  \
0                  11                      14               55610   
1                  33                       0               11675   
2                   9                       5               11051   
3                  20                      16               78469   
4                  20                      12               87900   
...               ...                     ...                

In [121]:
import pickle

feature_names = ["activities", "api_calls", "opcodes", "permissions", "receivers", "services", "system"]
lgbm_models = []
rfc_models = []
knearest_models = []
xgb_models = []
cat_models = []
bagging_models = []
scalers = []
tnn_models = []


for i, n in enumerate(feature_names):
    filename = n + '_scaler.sav'
    scalers.append(pickle.load(open("../models/Scaler/"+filename, 'rb')))

for i, n in enumerate(feature_names):
    filename = 'gsLGB_'+ n + '_model.sav'
    lgbm_models.append(pickle.load(open("../models/LightGBM/"+filename, 'rb')))
    
for i, n in enumerate(feature_names):
    filename = 'gsRFC_'+ n + '_model.sav'
    rfc_models.append(pickle.load(open("../models/Random_Forest_Classifier/"+filename, 'rb')))

for i, n in enumerate(feature_names):
    filename = 'gsKnearest_'+ n + '_model.sav'
    knearest_models.append(pickle.load(open("../models/Knearest/"+filename, 'rb')))

for i, n in enumerate(feature_names):
    filename = 'gsXGBM_'+ n + '_model.sav'
    xgb_models.append(pickle.load(open("../models/xgbm/"+filename, 'rb')))

for i, n in enumerate(feature_names):
    filename = 'catboost_'+ n + '_model.sav'
    cat_models.append(pickle.load(open("../models/Catboost/"+filename, 'rb')))
    
for i, n in enumerate(feature_names):
    filename = 'bagging_'+ n + '_model.sav'
    bagging_models.append(pickle.load(open("../models/Bagging/"+filename, 'rb')))

# for i, n in enumerate(feature_names):
#     filename = 'nn_'+ n + '_model.h5'
#     tnn_models.append(load_model("../models/nn/"+filename))
    
meta_model = pickle.load(open("../models/Meta/meta_logistic.sav", 'rb'))


/home/cristiankamia/anaconda3/envs/research_py37/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/cristiankamia/anaconda3/envs/research_py37/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.21.3 when using version 0.22. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [124]:
NUM_FEATURES = 7

In [135]:
def preprocess_data(data):

    scaled_features = scalers[2].transform(data)
    data_sc = pd.DataFrame(scaled_features)
    
    return data_sc

In [141]:
df_train_opcodes_sc = preprocess_data(df_train_opcodes.drop(['MW'], axis=1))

xgb_model = xgb_models[0].best_estimator_

In [144]:
df_test_opcodes_sc = preprocess_data(df_test_opcodes.drop(['MW'], axis=1))

In [143]:
xgb_model.fit(df_train_opcodes_sc, df_train_opcodes['MW'])

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.05, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=nan, n_estimators=1000, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [145]:
xgb_model.score(df_test_opcodes_sc, df_test_opcodes['MW'])

0.873504014543251

In [147]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold


stratifiedkfold = StratifiedKFold(n_splits=10)
scores = cross_val_score(xgb_model , df_test_opcodes_sc , df_test_opcodes['MW'], cv=stratifiedkfold, n_jobs=8)
print("Cross-Validation scores: {}".format(scores))
print("Average score: {}".format(np.mean(scores)))

Cross-Validation scores: [0.83812405 0.87424242 0.8469697  0.85757576 0.8530303  0.87424242
 0.84393939 0.86666667 0.86060606 0.87727273]
Average score: 0.859266950900839


In [149]:
df_test_opcodes['MW'].value_counts()

1    3364
0    3237
Name: MW, dtype: int64